version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: intershop-postgres
    environment:
      POSTGRES_DB: intershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      SPRING_JPA_PROPERTIES_HIBERNATE_CONNECTION_AUTOCOMMIT: "false"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intershop-network


  # Spring Boot Приложение
  app:
    build: .
    container_name: intershop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/intershop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - intershop-network

volumes:
  postgres_data:

networks:
  intershop-network:
