services:
  postgres:
    image: postgres:16
    container_name: intershop-postgres
    environment:
      POSTGRES_DB: intershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intershop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: intershop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - intershop-network
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: intershop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: prod
      PAYMENT_SERVICE_URL: http://host.docker.internal:8081
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://host.docker.internal:8082/realms/MyIntershop
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://host.docker.internal:8082/realms/MyIntershop
    depends_on:
      - postgres
      - redis
    networks:
      - intershop-network

  payment:
    build:
      context: ./payService
      dockerfile: Dockerfile
    container_name: intershop-payment
    ports:
      - "8081:8081"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://host.docker.internal:8082/realms/MyIntershop
      PAYMENT_HOSTNAME: payment
    networks:
      - intershop-network
  keycloak:
    container_name: Keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8082:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: intershop
      DB_USER: postgres
      DB_PASSWORD: 12345
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8082
      KEYCLOAK_HOSTNAME: keycloak
    volumes:
      - keycloak_data:/var/lib/keycloak/data
    networks:
      - intershop-network
    depends_on:
      - postgres
    command:
      - "start-dev"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
volumes:
  postgres_data:
  redis_data:
  keycloak_data:

networks:
  intershop-network: