services:
  postgres:
    image: postgres:16
    container_name: intershop-postgres
    environment:
      POSTGRES_DB: intershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intershop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: intershop-app
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/intershop
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: prod
      PAYMENT_SERVICE_URL: http://payment:8081
    depends_on:
      - postgres
    networks:
      - intershop-network

  payment:
      build:
        context: ./payService
        dockerfile: Dockerfile
      container_name: intershop-payment
      ports:
        - "8081:8081"
      networks:
        - intershop-network

volumes:
  postgres_data:

networks:
  intershop-network: