openapi: 3.0.3
info:
  title: Payment Service API
  description: RESTful API для управления балансом пользователя и проведения платежей
  version: 1.0.0
servers:
  - url: http://localhost:8081
tags:
  - name: Баланс
    description: Операции с балансом пользователя
  - name: Платежи
    description: Обработка платежей и списание средств
paths:
  /balance:
    get:
      tags:
        - Баланс
      summary: Получить текущий баланс пользователя
      description: Возвращает текущий баланс пользователя в формате JSON
      responses:
        '200':
          description: Успешное получение баланса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
              example:
                balance: 1000.0
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /payment:
    post:
      tags:
        - Платежи
      summary: Провести платеж
      description: Выполняет списание указанной суммы с баланса пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
            example:
              amount: 200.0
        description: Объект с суммой платежа
      responses:
        '200':
          description: Результат проведения платежа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                success: true
        '400':
          description: Неверные данные платежа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Внутренняя ошибка сервера
components:
  schemas:
    BalanceResponse:
      type: object
      properties:
        balance:
          type: number
          format: float
          description: Текущий баланс пользователя
      required:
        - balance
    PaymentRequest:
      type: object
      properties:
        amount:
          type: number
          format: float
          description: Сумма платежа
          minimum: 0.01
      required:
        - amount
    PaymentResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Успешно ли проведён платёж
      required:
        - success
    Error:
      type: object
      properties:
        error:
          type: string
          description: Описание ошибки
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
      required:
        - error
        - timestamp